spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
